What is Numpy?
1. Numpy is a library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. It is widely used in scientific computing, data analysis, and machine learning due to its performance and ease of use.
2. library is used for numerical computations and provides a high-performance multidimensional array object, as well as tools for working with these arrays.
3. linear algebra, Fourier transforms, and random number generation are some of the functionalities provided by Numpy.
4. Used for creating arrays, performing mathematical operations on arrays, and manipulating data in a vectorized manner.
5. Provides a convenient way to work with large datasets and perform complex mathematical operations efficiently.
6. Provides features for broadcasting, which allows for operations on arrays of different shapes and sizes without the need for explicit looping.
7. Provides a wide range of functions for array manipulation, including reshaping, indexing, slicing, and concatenation.
8. Provides support for reading and writing data to and from various file formats, including CSV, Excel, and HDF5.
9. Provides a rich set of functions for statistical analysis, including mean, median, standard deviation, and correlation.
10. Provides support for linear algebra operations, including matrix multiplication, eigenvalue decomposition, and singular value decomposition.
11. Provides support for random number generation, including sampling from various probability distributions and generating random numbers with specific properties.
12. Provides support for Fourier transforms, including discrete Fourier transforms and fast Fourier transforms.
13. Provides support for parallel computing, allowing for efficient execution of operations on large datasets using multiple CPU cores or GPUs.
14. Provides support for integration with other scientific computing libraries, such as SciPy and Pandas, allowing for seamless data analysis and manipulation.
15. Provides support for visualization, allowing for the creation of plots and graphs to visualize data and results.
16. Provides support for machine learning, allowing for the implementation of various algorithms and models for classification, regression, clustering, and dimensionality reduction.
17. Provides support for deep learning, allowing for the implementation of neural networks and other deep learning models using libraries such as TensorFlow and PyTorch.
18. Provides support for optimization, allowing for the implementation of various optimization algorithms for solving complex problems in various domains.
19. Provides support for signal processing, allowing for the implementation of various signal processing techniques for analyzing and manipulating signals in various domains.
20. Provides support for image processing, allowing for the implementation of various image processing techniques for analyzing and manipulating images in various domains.
21. Provides support for natural language processing, allowing for the implementation of various techniques for analyzing and manipulating text data in various domains.
22. Provides support for time series analysis, allowing for the implementation of various techniques for analyzing and manipulating time series data in various domains.
23. Provides support for geospatial analysis, allowing for the implementation of various techniques for analyzing and manipulating geospatial data in various domains.
24. Provides support for financial analysis, allowing for the implementation of various techniques for analyzing and manipulating financial data in various domains.
25. Provides support for scientific computing, allowing for the implementation of various techniques for analyzing and manipulating scientific data in various domains.
26. Provides support for engineering applications, allowing for the implementation of various techniques for analyzing and manipulating engineering data in various domains.
27. Provides support for medical applications, allowing for the implementation of various techniques for analyzing and manipulating medical data in various domains.
28. Provides features for data visualization, allowing for the creation of various types of plots and graphs to visualize data and results in various domains.
29. Provides features for operations on multi-dimensional arrays, metrics in Python, allowing for efficient manipulation and analysis of data in various domains.


1D Array

In [1]:

import numpy as np
a = np.array([[1, 2, 3]])
print(a)


[[1 2 3]]


2D Array

In [3]:
b =np.array([[4, 5, 6], [7, 8, 9]])
print(b)


[[4 5 6]
 [7 8 9]]


NDArray Object

In [4]:
c = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(c)   

[[10 11 12]
 [13 14 15]
 [16 17 18]]


Initializing Numpy Array

Initialize an array of 'x' X 'y' dimension with 0

In [5]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Arranging the numbers between x and y with an interval of z

In [18]:
np.arange(10,25,5)

array([10, 15, 20])

Arranging 'z' numbers between x and y

In [19]:
np.linspace(5,10,6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [22]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

Filling SAME number in a array of dimension x X Y

In [23]:
np.full((2, 2), 5)

array([[5, 5],
       [5, 5]])

In [24]:
np.full((2, 4), 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [25]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

Filling RANDOM numbers in a array of dimension x X y

In [26]:
np.random.random((2, 2))

array([[0.4620808 , 0.69029571],
       [0.86499646, 0.14011948]])

ndarray.shape

"Returns a tuple consisting of array dimensions. Can also be used to resize the array"

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

(2, 3)


In [28]:
a = np.array([[1, 2, 3, 4],[4, 5, 6, 4], [2, 1, 5, 6]])
print(a.shape)

(3, 4)


            ndarray.shape

"Returns a tuple consisting of array dimensions. Can also be used to resize the array"

In [ ]:

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a) # a. shape = (2, 3)
a. shape = (3, 2) # reshaping a to (3, 2) from (2, 3)
print(a) 
b = a # b is a reference to a, so any changes made to b will also affect a
b.shape=(6, 1) # reshaping b to (6, 1) from (3, 2)
# should know the exact row and column size to perform this action
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


ndarray.size

"Return the count of number of elements in an array."

In [48]:
a = np.arange(24)
print(a.size)

24


ndarray.ndim

" Returns the dimension of the array"

In [52]:
a = np.arange(24)
print(a.ndim)
b = a.reshape(2, 2, 6)
print(b.ndim)

1
3


ndarray.dtype

" Returns datatype of an array"

In [58]:
a = np.arange(24, dtype='float64')
print(a.size)
print(a.dtype)
b=a.reshape(4, 3, 2)
b

24
float64


array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]])

Addition using Numpy

In [61]:
a =np.sum([10, 20, 30])
print(a)

60


In [62]:
a, b = 10, 40
c= np.sum([a, b])
print(c)

50


In [ ]:
d = np.sum([[1, 2, 3, 4], [2, 3, 4, 9]], axis=0) # Sum along the columns
print(d)

d = np.sum([[3, 4, 2], [3, 4, 1]], axis=1) # Sum along the rows
print(d)

[ 3  5  7 13]
[9 8]


In [ ]:
np.subtract([10, 20, 30], [1, 2, 3])
np.divide([10, 20, 30], [1, 2, 3]) 
np.multiply([10, 20, 30], [1, 2, 3])
np.exp([1, 2, 3])
np.sqrt([1, 4, 9])  
np.sin(a)
np.cos(a)
np.log(a)

Array Comparison

In [75]:
# Element-wise comparison

a = [1, 2, 6]
b = [2, 6, 4]
c = [1, 2, 6]
#np.equal(a, b)

#np.equal(a, c)

# Array-wise Comparison
np.array_equal(a, b)



False

Aggregate Functions

In [76]:
print(np.sum(a)) # Array wise sum
print(np.min(a)) # Min of an array
print(np.mean(a)) # Mean of the array
print(np.median(a)) # Median of the array
print(np.corrcoef(a)) # Correlation coefficient of array
print(np.std(a)) # Standard Deviation of array

9
1
3.0
2.0
1.0
2.160246899469287


Concept of Broadcasting

In [81]:
a = np.array([[0, 0 ,0, 0], [5,5,5,5], [4,4,4,4], [6,6,6,6]])
b = np.array([[1, 2, 3, 4]])

print('First Array:\n', a, '\n')
print('Second array: \n', b, '\n')

print('First Array + Second Array \n', a+b)

First Array:
 [[0 0 0 0]
 [5 5 5 5]
 [4 4 4 4]
 [6 6 6 6]] 

Second array: 
 [[1 2 3 4]] 

First Array + Second Array 
 [[ 1  2  3  4]
 [ 6  7  8  9]
 [ 5  6  7  8]
 [ 7  8  9 10]]


Indexing in Python

"Index refers to a position"

In [102]:
a = ['M','o','n','t','y',' ','P', 'y', 't', 'h', 'o', 'n']
print(a[-12:8])



['M', 'o', 'n', 't', 'y', ' ', 'P', 'y']


Concatenating two arrays together

In [104]:
a = [1, 2, 3]
b = [3, 4, 5]
np.concatenate((a, b), axis=0)


array([1, 2, 3, 3, 4, 5])

In [ ]:
np.vstack((a, b)) # Stack arrays row-wise(vertically)

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
np.hstack((a, b)) # Stack arrays column-wise(horizontally)

array([1, 2, 3, 3, 4, 5])

In [107]:
np.column_stack((a, b)) # Combining column wise stacked array

array([[1, 3],
       [2, 4],
       [3, 5]])

Splitting Arrays

In [108]:
x = np.arange(16).reshape(4, 4)
print(x, '\n\n')
print(np.hsplit(x, 2), '\n\n')
print(np.hsplit(x, np.array([3, 6])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] 


[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]]), array([], shape=(4, 0), dtype=int64)]


Numpy Vs List: Memory Size

In [109]:
import sys
l = range(1000)
print(sys.getsizeof(10)* len(l))
array = np.arange(1000)
print(array.size*array.itemsize)

28000
8000


Numpy vs List: Speed

In [111]:
import time
def using_List():
    t1 = time.time()
    X = range(10000)
    Y = range(10000)
    Z = [X[i] + Y[i] for i in range(len(x))]
    return time.time() - t1

def using_Numpy():
    t1 = time.time()
    X = np.arange(10000)
    Y = np.arange(10000)
    Z = X + Y
    return time.time() - t1

t1 = using_List()
t2 = using_Numpy()

print(t1, t2)
print("As per the given example, Numpy is "+ str(t1/t2) +" time(s) faster")

5.245208740234375e-06 4.9591064453125e-05
As per the given example, Numpy is 0.10576923076923077 time(s) faster
