In [8]:
import numpy as np
# 1. Create a function that takes dimensions as tuples e.g. (3,3) and a numeric value and returns a Numpy array of the given dimension filled with the given value e.g.: solve((3,3), 5) will return [[5, 5, 5], [5, 5, 5], [5, 5, 5]]
def solve(dimensions, value):
    # Create a Numpy array of the given dimensions filled with the specified value
    array = np.full(dimensions, value)
    # arrayzeros = np.zeros(dimensions)
    return array # , arrayzeros

print(solve((3,3), 5))



[[5 5 5]
 [5 5 5]
 [5 5 5]]
